export const keywords = {
	Development: [
		"javascript",
		"typescript",
		"react",
		"angular",
		"callbacks",
		"higher order functions",
		"web storage api",
		"dom manipulation",
		"nginx",
		"magic link authentication",
		"sliding window technique",
		"view transitions",
		"front-end",
		"node.js",
		"express.js",
		"vue.js",
		"sass",
		"graphql",
		"rest api",
		"docker",
		"webpack",
		"git",
		"redux",
		"mvc architecture",
		"jenkins",
		"aws",
		"azure",
		"microservices",
		"oauth",
		"jwt",
		"continuous integration",
		"continuous deployment",
		"serverless",
		"api gateway",
	],

	Design: [
		"design",
		"designer",
		"designing",
		"graphic design",
		"illustration",
		"typography",
		"color theory",
		"branding",
		"motion graphics",
		"ui patterns",
		"material design",
		"adobe photoshop",
		"adobe illustrator",
		"sketch",
		"figma",
		"user flows",
		"visual hierarchy",
		"layout design",
	],
	UX: [
		"ux",
		"user experience",
		"user research",
		"wireframing",
		"prototyping",
		"usability testing",
		"interaction design",
		"information architecture",
		"persona creation",
		"accessibility",
		"user journey mapping",
		"heuristic evaluation",
		"cognitive psychology",
		"user-centered design",
		"design thinking",
		"empathy mapping",
		"user flows",
		"ethnographic study",
		"contextual inquiry",
		"service design",
	],
	UI: [
		"ui",
		"user interface",
		"visual design",
		"graphic design",
		"interface layout",
		"color theory",
		"typography",
		"branding",
		"UI patterns",
		"iconography",
		"interaction animation",
		"screen design",
		"responsive interface",
		"material design",
		"flat design",
		"UI kits",
		"mockups",
		"style guides",
		"Figma",
		"Sketch",
	],
	Productivity: [
		"productivity",
		"productivity tips",
		"time management",
		"task management",
		"kanban",
		"scrum",
		"agile methodology",
		"pomodoro technique",
		"goal setting",
		"efficiency hacks",
		"remote work",
		"work-life balance",
		"mind mapping",
		"personal development",
		"focus techniques",
		"project management tools",
		"email management",
	],
	Mobile: [
		"mobile",
		"mobile app",
		"mobile application",
		"ios development",
		"android development",
		"swift",
		"kotlin",
		"flutter",
		"react native",
		"xamarin",
		"mobile ui/ux",
		"app store optimization",
		"mobile testing",
		"cross-platform development",
		"mobile analytics",
		"gesture navigation",
		"mobile performance optimization",
		"push notifications",
	],
	Security: [
		"security",
		"security tips",
		"cybersecurity",
		"encryption",
		"penetration testing",
		"firewall",
		"vulnerability assessment",
		"malware analysis",
		"data privacy",
		"incident response",
		"network security",
		"cloud security",
		"biometric security",
		"two-factor authentication",
		"blockchain security",
		"cybersecurity regulations",
		"ethical hacking",
	],
};
